function S = importfile2d(filename, dataLines)
%IMPORTFILE Import data from a text file
%  [VARNAME3, VARNAME4, VARNAME7, VARNAME8] = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as column vectors.
%
%  [VARNAME3, VARNAME4, VARNAME7, VARNAME8] = IMPORTFILE(FILE,
%  DATALINES) reads data for the specified row interval(s) of text file
%  FILENAME. Specify DATALINES as a positive scalar integer or a N-by-2
%  array of positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  [VarName3, VarName4, VarName7, VarName8] = importfile("/home/scott/research/controlled-invariant/data_cart_ch/s1.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Apr-2025 11:58:38

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = [",", ";", "[", "]"];

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "l1", "u1", "Var5", "Var6", "l2", "u2", "a", "b", "l3", "u3"];
opts.SelectedVariableNames = ["l1", "u1", "l2", "u2", "l3", "u3"];
opts.VariableTypes = ["string", "string", "double", "double", "string", "string", "double", "double" "string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var5", "Var6"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var5", "Var6"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
N = height(tbl);
S = cell(N,1);
for i = 1:N
S{i} = interval([tbl.l1(i); tbl.l2(i); tbl.l3(i)], [tbl.u1(i); tbl.u2(i); tbl.u3(i)]);
end